# Generated by Django 4.1.1 on 2022-10-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='test@x.com', max_length=254),
            preserve_default=False,
        ),
    ]
